version: 2.1

orbs: 
    win: circleci/windows@2.2.0

jobs:
  build:
    working_directory: C:\Users\circleci\repo
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - C:\Users\circleci\repo\node_modules
      - run:
          name: Generate Builds
          command: npm run make  
      - store_artifacts:
          path: C:\Users\circleci\repo\out\make
      - run:
          name: Test builds
          command: npm test 
      - store_test_results:
          path: C:\Users\circleci\repo\test-results